### PR TITLE
trying to fix wrong heading

### PR DESCRIPTION
**Pull request by woensug-choi**
Trying to debug the wrong heading error.

The local direct commanding run test gave me the following results,
image

When running it with slocum_glider repo in docker using qq_t_50.mi, glider moves towards the north-west direction. 
image

The commands sent by the sim driver reports it's ordering the glider to head 5.3290534 (about 305 degrees).
```
---
header:
  seq: 1331
  stamp:
    secs: 5358
    nsecs: 400000000
  frame_id: ''
pitch_cmd_type: 3
target_pitch_value: 0.209000006318
motor_cmd_type: 0
target_motor_cmd: 0.0
rudder_control_mode: 1
target_heading: 5.32905340195
rudder_angle: 4
target_rudder_angle: 5.32905340195
target_pumped_volume: -226.0
```

I guess the sim driver should command to head something like 35 degrees (90 degrees more than what it's commanding now). @daewok Maybe I'm putting out the wrong data for the sim driver. How does it determine the commanding value for heading?

### CODE REVIEW

**Comment by woensug-choi** [comment]
Maybe adding pi/2 here? 
https://gitlab.com/sentinel-aug/ros/slocum_glider/-/blob/master/slocum_glider_extctl_sim/src/slocum_glider_extctl_sim/behaviors/goto_wpt.py#L62

**Comment by woensug-choi** [comment]
I have been testing things out with the [`heading_bug`](https://gitlab.com/sentinel-aug/ros/slocum_glider/-/tree/heading_bug) branch on the slocum glider repo at the Girlab. The branch is based on the `really_go_to_waypoint` branch rebased to `master`. I've been committing and reverting multiple times on the way to understand the codes. Not in a good shape for merge. But worth testing things out.

**Comment by daewok** [comment]
The extctl_sim driver bug was fixed by https://gitlab.com/sentinel-aug/ros/slocum_glider/-/merge_requests/26.

I also pushed some more fixes to this branch for the dead reckoning code.

**Comment by woensug-choi** [comment]
The heading bug is fixed. merging this PR before it gets too large.

**Pull request merged**
